src/windows_port.cc
didn't compile with msvs 2015 RC due to snprintf now finally being supported by vs
=> support for msvs 2015 RC

CMakeLists.txt
Previously NOTHREADS was being defined but the code
in mutex.h checks for NO_THREADS.
This was found with ports gflags to emscripten which doesn't
support threading:
https://chromium.googlesource.com/webports.git/+/9001e2ce36fa7959dbefcd1f3aabcaf4a2de9248/ports/gflags/nacl.patch
=> Define NO_THREADS in when building without threads

CMakeLists.txt
Like windows need a .lib to contain symbol of the .dll, the static library and the dynamic cannot have the same name on windows.
=> handle generation of dynamic and static library on windows.

CMakeLists.txt
This patch has two consequences:
* previously in lib there would be a file like `libgflags.so.2.2.0` and a symlink named `libgflags.so.2` and `libgflags.so`
* previously the `SONAME` in the ELF files would be `libgflags.so.2`
This change updates the `SONAME` to `libflags.so.2.2` and adds an extra symlink `libgflags.so.2.2`.
Note that this change is already being done upstream by the Fedora packagers.
**Without This Patch**
```
$ ls lib/
libgflags_nothreads.so  libgflags_nothreads.so.2  libgflags_nothreads.so.2.2.0  libgflags.so  libgflags.so.2  libgflags.so.2.2.0
$ find lib -type f -exec readelf -d {} \; | grep SONAME
0x000000000000000e (SONAME)             Library soname: [libgflags.so.2]
0x000000000000000e (SONAME)             Library soname: [libgflags_nothreads.so.2]
```
**With This …
=> properly export the .so minor version

src/gflags.cc, src/gflags.h.in, src/gflags_declare.h.in, src/gflags_ns.h.in, test/gflags_unittest.cc
From #99, “Given that there is an unsigned flag type for 64-bit
integers, it is probably reasonable to request/expect the same for
32-bit integers.”
=> Support uint32 as flag type

BUILD
Add gendir to the include path so that building with bazel doesn't complain config.h can't be found.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gflags/gflags/150)
=> Fix bazel build

src/gflags_completions.cc
This is quite a trivial change =)
Could you explain please, what is the status of C++11 features in this project? Are they allowed or not?
If the latter, what do you think about using some of C++11\14\17 features?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gflags/gflags/155)
=> Add missing reference symbol to a function parameter.

src/gflags.cc, test/gflags_unittest.cc
Hi!
While playing with the code I discovered that typename for uint32 was declared with a typo.
Also I fixed some unittests related to that.
PTAL.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gflags/gflags/156)
=> Fix incorrect flag value typename for uint32.

src/gflags.cc, src/gflags.h.in, test/gflags_unittest.cc
Hi!
This is a part of #157 issue.
Here I tried to use enum value instead of `char*` constant to specify flag value type.
It is not a perfect solution, and I will be glad to discuss it.
PTAL.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gflags/gflags/158)
=> Use enum to specify flag value type.

.travis.yml
This a part of #159
It should test that the library and tests can be builded and CMake based tests can pass.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gflags/gflags/160)
=> Enable Travis CI for Linux and OSX builds

appveyor.yml
Hi!
This is another part of #159 issue.
Project https://ci.appveyor.com/ is like Travis, but for Windows only.
It requires to login and add a project from Github like Travis does.
I've failed to run tests there for Release build (not sure why ATM), but it can build from sources, for example see logs https://ci.appveyor.com/project/dreamer-dead/gflags
When I will fix my Windows build machine with new WinSDK 10, I can make further improvements on this config.
PTAL.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gflags/gflags/161)
=> Add initial AppVeyor config.

appveyor.yml
Hi!
With this I was able to build and run tests (except `strip_flags_binary` one) for both configurations.
For example, https://ci.appveyor.com/project/dreamer-dead/gflags/build/1.0.36
With -VV ctest generate a lot of logs and it stuns AppVeyor, will look on failed test later.
Locally it passes on my Windows machine.
#159 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gflags/gflags/162)
=> Run build via cmake and run tests.

test/CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gflags/gflags/163)
=> fix: Run strip_flags_binary test only for release configurations

appveyor.yml
After your changes in #163 , it is possible to clean out tests filter.
It seems that #159 can be closed after merging this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gflags/gflags/165)
=> Remove filter for excluded tests from AppVeyor config.

src/gflags.cc, src/gflags_declare.h.in
Hi!
It is a fix to shared library build.
Unfortunately, I missed `GFLAGS_DLL_DECL` attribute for templates =(
It seems that we need a shared build configuration on CI server.
Also, I tried to fix some compiler and linker warnings,
- about OS_WINDOWS, because shlwapi.h header also can define it (but can be avoided).
- about warning LNK4217: locally defined symbol FLAGS_tryfromenv. I saw that you fixed that some time ago, but I had this warning.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gflags/gflags/166)
=> Fix Windows linker errors and warnings.

src/gflags_reporting.cc
A line in `gflags_reporting.cc` was causing an error on building with `-Werror` because of signed and unsigned integral comparisons.  This commit fixed that by declaring the integer used for length comparisons to be unsigned and of type `size_t`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gflags/gflags/168)
=> Fix unsigned comparison error in gflags_reporting.cc

src/gflags.cc
I noticed that error messages from GFlags were being truncated, and it
turns out the code limits it to 255 characters. This removes the 255 char
buffer and prints directly to stderr.
I also couldn't find any justification in the commit that introduced this char
[buf](https://github.com/gflags/gflags/commit/917f4e7bf3c36b4c56a77faca639758d3aca2a92#diff-6a83ed5fb1a483481f248c62830bb566R180).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gflags/gflags/175)
=> Fix error messages to not truncate to 255 characters

CMakeLists.txt, cmake/config.cmake.in
See #174. Actually, there was no mistake in the use of the `install(EXPORT)` command. However, to be save, use `EXPORT_NAME` variable in `gflags-config.cmake.in` instead and avoid need for providing a different installation file name. Maybe the issue reported in #174 was caused by another CMake version. I checked the documentation of 2.8, 3.0, and 3.7, however, and in all cases the file name argument option is `FILE` is it has been used before...
=> enh: Avoid use of install(EXPORTS) FILE option

CMakeLists.txt, cmake/utils.cmake
As discussed in #174, by default add path to `gflags-config.cmake` of installation in `CMAKE_INSTALL_PREFIX` to CMake's user package registry instead of the build directory.
=> enh: Add option to add installation to CMake’s package registry

CMakeLists.txt, src/config.h.in, src/gflags_declare.h.in
Set `GFLAGS_IS_A_DLL` on Windows to either 1 or 0 depending on whether target is a shared or static library.
Closes #89.
=> enh: Set GFLAGS_IS_A_DLL in INTERFACE_COMPILE_DEFINITIONS

CMakeLists.txt, src/completions.cc, src/gflags.cc, src/gflags.h.in, src/mutex.h, src/reporting.cc, src/util.h
Minor change. Just rename some `.cc` files to get rid of obsolete `gflags_` prefix. Still needed for public headers, though, in case these are in a namespace / include directory not exclusive to the gflags library (e.g., `google/`).
=> enh: Rename private sources, include public headers with rel path

CMakeLists.txt, src/gflags.cc, src/gflags.h.in, src/gflags_completions.cc, src/gflags_reporting.cc, src/mutex.h, src/util.h
Ok, just figured through the failing tests that it is desirable to have the reporting module called `gflags_reporting.cc` in the help output... gflags is just so different from other command-line parsing libraries...
Reverts gflags/gflags#190
=> Revert "enh: Rename private sources, include public headers with rel path"

BUILD, WORKSPACE, bazel/gflags.bzl, src/gflags.cc, src/gflags.h.in, src/gflags_completions.cc, src/gflags_reporting.cc, src/mutex.h
Refactored Bazel BUILD rules:
- Added `gflags_nothreads` target.
- Added rules to generate `gflags/gflags_google.h` header file with symbols imported into `google` namespace to maintain backwards compatibility (for now).
- Include public header files using interface include path, e.g., `gflags/gflags.h`, in all files.
- Added `WORKSPACE` file as suggested by @yasushi-saito  in #181.
Verify before merge:
- ~~Check Bazel build on Windows 7.~~
Closes #153, #179.
=> enh: Bazel BUILD, add WORKSPACE file

CMakeLists.txt
Leave `CMAKE_MODULE_PATH` for users to define where `find_package` modules are.
=> fix: Include utils by file instead of CMAKE_MODULE_PATH search

src/gflags.cc
=> fix: Remove unused program_name variable

CMakeLists.txt
Seems I used a condition before that was always true because a CMake bug wasn't fixed yet at the time...
=> fix: Enable language C for older CMake versions when needed

bazel/gflags.bzl
If you don't do this, importing as an external repo doesn't work properly.
In the current version I ended up with system include lines like this:
-isystem bazel-out/local_linux-opt/genfiles/external/gflags/bazel-out/local_linux-opt/genfiles
which is not correct.
=> Changed include directory in bazel build

src/windows_port.h
Warnings will spit out on newer compilers due to PRI* being redefined.
Tested with VC++ 2015 and 2017. [Blog post](https://blogs.msdn.microsoft.com/vcblog/2013/07/19/c99-library-support-in-visual-studio-2013/) describing the defines being added in 2013.
=> Use inttypes.h on VC++ 2013 and up

.gitignore
Add some entries to `.gitignore` relating to symbolic links to products created by Bazel.
=> git: Ignore symbolic links created by Bazel build tool

src/gflags.cc
Get rid of unused `kRootDir` once and for all. If such file name cleaning is desired, we need to come up with a better/more sustainable solution. Keeping this meaningless code around just causes confusion.
See also #86.
=> fix: Remove obsolete and unused CleanFileName code

INSTALL.md
https://github.com/gflags/gflags/issues/251
=> Remove installation guide's recommendation to use Bazel's bind().

CMakeLists.txt, cmake/config.cmake.in, test/config/CMakeLists.txt
- add VERSION to project command
- remove uneeded `enable_testing()` command
- Move gflags target(s) to gflags:: namespace
note: [gRPC CMakeLists.txt](https://github.com/grpc/grpc/blob/master/cmake/gflags.cmake#L30) seems already to look for target gflags::gflags ...
=> few CMake Update

src/gflags.h.in
@rnburn could you please check this closes your warning #262?
=> fix: Declare FALGS_no##name variables as static

src/config.h, src/gflags_declare.h.in
Fixes #267.
Tested with https://github.com/gflags/example project in Ubuntu WSL using GCC 7.3 (Ubuntu 7.3.0-27ubuntu1~18.04).
=> fix: Use 'default' visibility for GCC

cmake/package.pc.in
More consistent with other pkgconfig files.
No functional difference.
=> package.pc.in: bin and libdir to exec_prefix

src/gflags_reporting.cc
If the workaround in issue #43 is used along with the define of
STRIP_FLAG_HELP to 1, there would be a wrong "No modules matched"
message been print at end of the usage message.
That's because we continue the loop if we see strip flag help value and
never set the `found_match` flag to true even if we found a match.
By moving the set statement above the continue, we can avoid this wrong
message.
=> Avoid no-match message in case STRIP_FLAG_HELP been set

src/gflags.h.in
```
gflags.h(226): warning: attribute "visibility" does not apply here
```
The visibility attribute applies to symbols like functions and variables. A definition of an enumeration type that doesn't contain a variable name doesn't create any symbols.
=> remove visibility attribute where it does not apply

src/gflags_completions.cc
INFO: From Compiling external/com_github_gflags_gflags/src/gflags_completions.cc:
external/com_github_gflags_gflags/src/gflags_completions.cc:459:16: warning: code will never be executed [-Wunreachable-code]
DVLOG(3) << "Result: most-common match";
^~
1 warning generated.
=> Remove unreachable code

bazel/expanded_template/BUILD, bazel/expanded_template/expand_template.cc, bazel/expanded_template/expanded_template.bzl, bazel/gflags.bzl
Bazel genrules require a msys shell to execute
shell commands. Replace the genrules with a
simple C++ regex replacement binary.
Fixes #303.
=> Remove msys dependency for Windows.

src/gflags_completions.cc
GCC gives an implicit-fallthrough warning (included in -Wextra). C++17 has the `[[fallthrough]]` attribute, and GCC7+ has `__attribute__((fallthrough))`, but I didn't want to require either so I refactored the switch into if statements.
=> Remove fallthrough switch case

doc/index.html
In bazel WORKSPACE, method `git_repository` need a list as `tags` parameter.
=> Update index.html dependency with Bazel section.

bazel/expanded_template/expand_template.cc
This fixes a continuous build
(https://travis-ci.org/github/google/perf_data_converter/jobs/714589290)
running on Ubuntu 16.04 using gcc-4.8.
TESTED=Fresh install and system configuration following https://github.com/google/perf_data_converter/blob/master/.travis.yml
=> Include string.h for strchr and strcmp.

test/gflags_build.py.in
python2 is EOL, swith shebang to python3
Signed-off-by: Changqing Li <changqing.li@windriver.com>
=> switch shebang to python3

BUILD
Currently, bazel build result will have `gflags` namespace while `cmake` have `google` namespace, this PR will make bazel also use `google` namespace
=> make bazel use same namespace with cmake

doc/index.html
This PR adds an `id` attribute to the `--flagfiles` flag header so that a link in the earlier part of the document works. i.e.
This link
Now links to this section
Previously it did not link anywhere.
=> Update docs. Add id to --flagfile so it can be jumped to

CMakeLists.txt, test/CMakeLists.txt
Hi!
I'm a part of the Open Source Software team at BlackBerry QNX and have been working to add QNX support to open-source libraries. we do maintain our own forks of some projects, but with smaller changes such as the ones required to cross-compile gflags we like to upstream them so that support is more accessible.
For more context- QNX is a RTOS mainly used in industry for automotive and robotics applications, but recently has been made free for non-commercial use. It is cross-compiled using a gcc toolchain, but due to being POSIX compliant works with most libraries with little modification.
The only changes I needed to make to get gflags to cross compile and pass tests on QNX was to modify the `INCLUDE_INSTALL_DIR` in CMakeLists.txt to point to a staging area, and compiling and …
=> QNX Support
