gflags/gflags

src/gflags_completions.cc, src/windows_port.cc, src/windows_port.h, test/gflags_declare_flags.cc, test/gflags_unittest.cc
Includes some strict warnings about missing declarations and some fixes for MSVC2015.
=> Resolve some compiler warnings

src/gflags.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gflags/gflags/152)
=> Fix bug about LRLF

.travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gflags/gflags/164)
=> test: Travis CI build static+shared in Release+Debug

appveyor.yml
Build on AppVeyor may fail because of not merged PR #166 
I can rebase then to check that it will be fixed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gflags/gflags/167)
=> Add shared library build to the AppVeyor CI config.

src/gflags.h.in
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gflags/gflags/170)
=> Fix make error for lacking namespace

src/gflags.cc
Closes #77.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gflags/gflags/173)
=> fix: Validate modified flags only once

src/gflags.cc, test/gflags_unittest.cc
Here's the most straight-forward implementation of #177, seems to work with some brief testing of my app.
=> Convert dashes to underscores for unknown flags (#177)

CMakeLists.txt, cmake/package.pc.in
=> enh: Configure and install pkg-config .pc file

BUILD
=> fix: Add -lpthread to link Bazel BUILD options

ChangeLog.txt, README.md
See ChangeLog revision.
Closes #172.
=> Release v2.2.0

src/gflags.h.in
=> Fix statically linked gflags library with MSVC

CMakeLists.txt
=> Fix installation path of runtime libraries on Windows

src/gflags.cc
Applying the fix proposed in https://github.com/gflags/gflags/issues/214
=> Fixing AddSan Bug in gflags.cc

src/gflags_declare.h.in
Fixes https://github.com/PaddlePaddle/Paddle/issues/3277
=> Remove using ::fLS::clstring;

src/gflags.cc
=> Removed unused functions.

test/gflags_declare_test.cc
repair wrong namespace problem
=> repair wrong namespace problem

src/gflags.cc
Minor cleanup of merged pull request.
=> fix: Indentation, use spaces instead of real tabs

.gitignore, src/gflags.h.in
@rnburn could you check that this solves your issue #261?
=> fix: Declare FlagRegisterer c’tor explicit template instantiations as extern

src/gflags.cc, src/gflags_completions.cc
Fixes warnings produced by latest PVS Studio with VS 2015. Closes #228.
=> fix: PVS Studio warnings

src/gflags.cc
=> fix: Build with _UNICODE support on Windows

src/windows_port.h
=> fix: Build with MinGW version after Nov 2016

MODULE.bazel
Add MODULE.bazel file to support Bzlmod
=> Add MODULE.bazel file to support Bzlmod

ChangeLog.txt, README.md, doc/index.html, src/gflags_completions.cc, src/gflags_completions.h.in, src/gflags_reporting.cc, test/CMakeLists.txt
=> Fix spelling

CMakeLists.txt
close issue https://github.com/gflags/gflags/issues/306
=> cmake: export `gflags_nothreads_static` into one export set by subproject default

ChangeLog.txt
**Changes**
line 5 FALGS -> FLAGS
line 34 Meregd -> Merged
line 250 serliaizing -> serializing
**Issue**
Resolves gflags/gflags#361
=> Spell-checked ChangeLog.Txt

CMakeLists.txt, test/config/CMakeLists.txt, test/nc/CMakeLists.txt
closes #366 
relates to https://github.com/Homebrew/homebrew-core/pull/217424
=> build: support cmake 4.0
